#!/usr/bin/env python3
"""Generate simple DOCX, XLSX, and PDF files to verify the installation."""
import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="outputs/demo")
    args = parser.parse_args()
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    from docx import Document
    doc = Document()
    doc.add_heading("Office Agent Skills Demo", 0)
    doc.add_paragraph("Generated by the open-source office-agent-skills example.")
    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    table.rows[0].cells[0].text = "Item"
    table.rows[0].cells[1].text = "Value"
    for item, value in [("DOCX", "Created"), ("XLSX", "Created"), ("PDF", "Created")]:
        cells = table.add_row().cells
        cells[0].text, cells[1].text = item, value
    doc.save(out / "report.docx")

    from openpyxl import Workbook
    from openpyxl.chart import BarChart, Reference
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"
    ws.append(["Month", "Revenue"])
    for row in [("January", 1200), ("February", 1650), ("March", 2100)]:
        ws.append(row)
    ws.freeze_panes = "A2"
    chart = BarChart()
    chart.title = "Revenue"
    chart.add_data(Reference(ws, min_col=2, min_row=1, max_row=4), titles_from_data=True)
    chart.set_categories(Reference(ws, min_col=1, min_row=2, max_row=4))
    ws.add_chart(chart, "D2")
    wb.save(out / "report.xlsx")

    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen.canvas import Canvas
    pdf = Canvas(str(out / "report.pdf"), pagesize=A4)
    pdf.setTitle("Office Agent Skills Demo")
    pdf.drawString(72, 780, "Office Agent Skills Demo")
    pdf.drawString(72, 750, "This PDF was generated with ReportLab.")
    pdf.save()
    print(f"Created files in {out.resolve()}")


if __name__ == "__main__":
    main()
